make:
	g++  -Wall -Werror -c router.cpp send.cpp utils.cpp vector_operations.cpp recive.cpp
	g++ -o router.out router.o send.o utils.o vector_operations.o recive.o
clean:
	rm -f *.o

distclean:
	rm -f *.o *.out