<?xml version="1.0" encoding="utf-8"?><Database Name="zadanie2l6" Class="StronyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=zadanie2l6;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zadanie2l6ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Strony" Member="Strony">
    <Type Name="Strony">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Strona" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>